openapi: 3.0.0
info:
  title: simple-api
  version: 0.2.0
paths:
  /hello:
    get:
      summary: Returns a Hello world to the user
      responses:
        '200':
          description: A simple hello world!
          content:
            application/json; charset=utf-8:
              example:
                message: Hello from a mocked response!
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message